# Generated by Django 5.1.4 on 2025-02-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fullname_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='fullname',
        ),
    ]
