# Generated by Django 5.1.4 on 2025-02-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_username_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreindRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('rece', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
