# Generated by Django 5.1.4 on 2025-02-08 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_freindrequest_rece_alter_freindrequest_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('rece_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rece_msg', to=settings.AUTH_USER_MODEL)),
                ('send_msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_msg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
