# Generated by Django 5.1.4 on 2025-02-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='freindrequest',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
