# Generated by Django 5.1.4 on 2025-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_freindrequest_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default='BlueTalks User ', max_length=400),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='distt',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
