# Generated by Django 5.1.4 on 2025-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_about_user_country_user_distt_user_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='suggest',
            field=models.BooleanField(default=False),
        ),
    ]
