# Generated by Django 5.1.4 on 2025-02-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_search_user_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='search',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='suggest',
            field=models.BooleanField(default=True),
        ),
    ]
