# Generated by Django 5.1.4 on 2025-02-23 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_search_alter_user_suggest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.CharField(default='cursive', max_length=100)),
                ('size', models.IntegerField(default=15)),
                ('color', models.CharField(max_length=20)),
                ('bg1', models.CharField(max_length=20)),
                ('bg2', models.CharField(max_length=20)),
                ('border', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
