# Generated by Django 5.1.4 on 2025-02-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_themes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themes',
            name='color',
        ),
        migrations.AddField(
            model_name='themes',
            name='color_rece',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='themes',
            name='color_send',
            field=models.CharField(default='', max_length=20),
        ),
    ]
