# Generated by Django 5.1.4 on 2025-03-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_themes_color_themes_color_rece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='bg1',
            field=models.CharField(default='#262626', max_length=20),
        ),
        migrations.AlterField(
            model_name='themes',
            name='bg2',
            field=models.CharField(default='#000', max_length=20),
        ),
        migrations.AlterField(
            model_name='themes',
            name='border',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AlterField(
            model_name='themes',
            name='color_rece',
            field=models.CharField(default='Green', max_length=20),
        ),
        migrations.AlterField(
            model_name='themes',
            name='color_send',
            field=models.CharField(default='Red', max_length=20),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
